name: Run Tests

on:
  push:
    paths:
      - 'solutions/*.c'
      - 'solutions/*.cpp'
      - 'solutions/*.py'
      - 'solutions/*.java'

jobs:
  detect-language:
    runs-on: ubuntu-latest
    outputs:
      lang: ${{ steps.detect.outputs.lang }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Detect Language
        id: detect
        run: |
          if ls solutions/*.c 1> /dev/null 2>&1; then
            echo "lang=c" >> $GITHUB_ENV
          elif ls solutions/*.cpp 1> /dev/null 2>&1; then
            echo "lang=cpp" >> $GITHUB_ENV
          elif ls solutions/*.py 1> /dev/null 2>&1; then
            echo "lang=python" >> $GITHUB_ENV
          elif ls solutions/*.java 1> /dev/null 2>&1; then
            echo "lang=java" >> $GITHUB_ENV
          fi

  run-tests:
    needs: detect-language
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run C Tests
        if: env.lang == 'c'
        run: |
          gcc solutions/*.c -o solution
          ./solution < tests/c_testcases.txt
      
      - name: Run C++ Tests
        if: env.lang == 'cpp'
        run: |
          g++ solutions/*.cpp -o solution
          ./solution < tests/cpp_testcases.txt
      
      - name: Run Python Tests
        if: env.lang == 'python'
        run: |
          python3 solutions/*.py < tests/python_testcases.txt
      
      - name: Run Java Tests
        if: env.lang == 'java'
        run: |
          javac solutions/*.java
          java -cp solutions $(basename $(ls solutions/*.java .java)) < tests/java_testcases.txt