name: Run Code Tests

on:
  push:
    paths:
      - "solutions/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ openjdk-17-jdk python3

      # Run C tests
      - name: Compile and Run C Program
        if: hashFiles('solutions/*.c') != ''
        run: |
          gcc solutions/*.c -o solution_c
          echo "Test Case 1: Input 5 10" && echo "5 10" | ./solution_c
          echo "Test Case 2: Input 3 7" && echo "3 7" | ./solution_c

      # Run C++ tests
      - name: Compile and Run C++ Program
        if: hashFiles('solutions/*.cpp') != ''
        run: |
          g++ solutions/*.cpp -o solution_cpp
          echo "Test Case 1: Input 5 10" && echo "5 10" | ./solution_cpp
          echo "Test Case 2: Input 3 7" && echo "3 7" | ./solution_cpp

      # Run Python tests
      - name: Run Python Program
        if: hashFiles('solutions/*.py') != ''
        run: |
          echo "Test Case 1: Input 5 10" && echo "5 10" | python3 solutions/*.py
          echo "Test Case 2: Input 3 7" && echo "3 7" | python3 solutions/*.py

      # Run Java tests
      - name: Compile and Run Java Program
        if: hashFiles('solutions/*.java') != ''
        run: |
          javac solutions/*.java
          echo "Test Case 1: Input 5 10" && echo "5 10" | java Solution
          echo "Test Case 2: Input 3 7" && echo "3 7" | java Solution
