name: Run Code Submissions

on:
  push:
    paths:
      - "/*.java"
      - "/*.c"
      - "/*.cpp"
      - "/*.py"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Language
        id: detect-language
        run: |
          FILE=$(find main -type f \( -name ".java" -o -name ".c" -o -name ".cpp" -o -name ".py" \) | head -n 1)
          echo "Detected file: $FILE"
          if [[ $FILE == main/*.java ]]; then
            echo "LANGUAGE=java" >> $GITHUB_ENV
          elif [[ $FILE == main/*.c ]]; then
            echo "LANGUAGE=c" >> $GITHUB_ENV
          elif [[ $FILE == main/*.cpp ]]; then
            echo "LANGUAGE=cpp" >> $GITHUB_ENV
          elif [[ $FILE == main/*.py ]]; then
            echo "LANGUAGE=python" >> $GITHUB_ENV
          else
            echo "No valid file detected!"
            exit 1
          fi

      - name: Run Tests
        run: |
          case $LANGUAGE in
            java)
              javac main/Main.java testcases/javatest.java
              java -cp testcases $(basename testcases/javatest.java .java)
              ;;
            c)
              gcc main/main.c testcases/ctest.c -o ctest
              ./ctest
              ;;
            cpp)
              g++ main/main.cpp testcases/cpptest.cpp -o cpptest
              ./cpptest
              ;;
            python)
              python3 testcases/pythontest.py
              ;;
            *)
              echo "No valid test file found!"
              exit 1
              ;;
          esac
