name: Run Code Submissions

on:
  push:
    paths:
      - "main/**/*.java"
      - "main/**/*.c"
      - "main/**/*.cpp"
      - "main/**/*.py"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ openjdk-17-jdk python3 python3-pip

      - name: Get Modified File
        id: detect-file
        run: |
          # Get the latest modified file in the push
          FILE=$(git diff --name-only HEAD~1 HEAD | grep -E 'main/.*\.(java|c|cpp|py)$' | head -n 1)
          echo "Modified file detected: $FILE"

          if [[ -z "$FILE" ]]; then
            echo "No valid modified file detected!"
            exit 1
          fi

          echo "SUBMITTED_FILE=$FILE" >> $GITHUB_ENV

          # Detect language
          if [[ $FILE == *.java ]]; then
            echo "TEST_FILE=testcases/MainTest.java" >> $GITHUB_ENV
            echo "LANGUAGE=Java" >> $GITHUB_ENV
          elif [[ $FILE == *.c ]]; then
            echo "TEST_FILE=testcases/ctest.c" >> $GITHUB_ENV
            echo "LANGUAGE=C" >> $GITHUB_ENV
          elif [[ $FILE == *.cpp ]]; then
            echo "TEST_FILE=testcases/cpptest.cpp" >> $GITHUB_ENV
            echo "LANGUAGE=C++" >> $GITHUB_ENV
          elif [[ $FILE == *.py ]]; then
            echo "TEST_FILE=testcases/pythontest.py" >> $GITHUB_ENV
            echo "LANGUAGE=Python" >> $GITHUB_ENV
          else
            echo "Unsupported file type!"
            exit 1
          fi

      - name: Debug - Show Detected File & Language
        run: |
          echo "Submitted File: $SUBMITTED_FILE"
          echo "Test File: $TEST_FILE"
          echo "Language: $LANGUAGE"

      - name: Compile and Run Java Program
        if: env.LANGUAGE == 'Java'
        run: |
          echo "Compiling Java files..."
          javac -d . $SUBMITTED_FILE $TEST_FILE
          if [ $? -eq 0 ]; then
            echo "Running Java test..."
            java -cp . testcases.MainTest
          else
            echo "Java compilation failed!"
            exit 1
          fi

      - name: Compile and Run C Program
        if: env.LANGUAGE == 'C'
        run: |
          echo "Compiling C program..."
          gcc $SUBMITTED_FILE $TEST_FILE -o ctest
          if [ $? -eq 0 ]; then
            echo "Running C test cases..."
            ./ctest
          else
            echo "C test failed!"
            exit 1
          fi

      - name: Compile and Run C++ Program
        if: env.LANGUAGE == 'C++'
        run: |
          echo "Compiling C++ program..."
          g++ $SUBMITTED_FILE $TEST_FILE -o cpptest
          if [ $? -eq 0 ]; then
            echo "Running C++ test cases..."
            ./cpptest
          else
            echo "C++ test failed!"
            exit 1
          fi

      - name: Run Python Program
        if: env.LANGUAGE == 'Python'
        run: |
          echo "Running Python test cases..."
          python3 -m unittest testcases.pythontest
          if [ $? -ne 0 ]; then
            echo "Python test failed!"
            exit 1
          fi
