name: Run Code Tests

on:
  push:
    paths:
      - "solutions/**"
  pull_request:
    paths:
      - "solutions/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ openjdk-17-jdk python3

      - name: Detect Changed Files
        id: changed-files
        run: |
          BEFORE_COMMIT="${{ github.event.before }}"
          if [ -z "$BEFORE_COMMIT" ] || ! git cat-file -e "$BEFORE_COMMIT"^{commit}; then
            BEFORE_COMMIT=$(git rev-list --max-parents=0 HEAD)
          fi
          CHANGED_FILES=$(git diff --name-only "$BEFORE_COMMIT" "${{ github.sha }}")
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Determine File Type
        id: determine-file
        run: |
          if echo "$CHANGED_FILES" | grep -qE '\.c$'; then
            echo "language=C" >> $GITHUB_ENV
            echo "::set-output name=language::C"
          elif echo "$CHANGED_FILES" | grep -qE '\.cpp$'; then
            echo "language=C++" >> $GITHUB_ENV
            echo "::set-output name=language::C++"
          elif echo "$CHANGED_FILES" | grep -qE '\.py$'; then
            echo "language=Python" >> $GITHUB_ENV
            echo "::set-output name=language::Python"
          elif echo "$CHANGED_FILES" | grep -qE '\.java$'; then
            echo "language=Java" >> $GITHUB_ENV
            echo "::set-output name=language::Java"
          else
            echo "No relevant file changes detected."
            exit 1
          fi

      - name: Compile and Run C Program
        if: steps.determine-file.outputs.language == 'C'
        run: |
          gcc solutions/*.c -o solution_c
          ./solution_c < test_cases/input.txt

      - name: Compile and Run C++ Program
        if: steps.determine-file.outputs.language == 'C++'
        run: |
          g++ solutions/*.cpp -o solution_cpp
          ./solution_cpp < test_cases/input.txt

      - name: Run Python Program
        if: steps.determine-file.outputs.language == 'Python'
        run: |
          python3 solutions/*.py < test_cases/input.txt

      - name: Compile and Run Java Program
        if: steps.determine-file.outputs.language == 'Java'
        run: |
          javac solutions/*.java
          java -cp solutions Solution < test_cases/input.txt
