name: Run Code Tests

on:
  push:
    paths:
      - "solutions/**"
  pull_request:
    paths:
      - "tests/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git diff

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ openjdk-17-jdk python3

      - name: Detect Changed Files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            c:
              - 'solutions/**/*.c'
            cpp:
              - 'solutions/**/*.cpp'
            python:
              - 'solutions/**/*.py'
            java:
              - 'solutions/**/*.java'

      - name: Compile and Run C Program
        if: steps.filter.outputs.c == 'true'
        run: |
          gcc solutions/main.c -o solution_c
          OUTPUT=$(./solution_c < tests/test.c)
          echo "$OUTPUT"
          echo "$OUTPUT" | tee results.log

      - name: Compile and Run C++ Program
        if: steps.filter.outputs.cpp == 'true'
        run: |
          g++ solutions/main.cpp -o solution_cpp
          OUTPUT=$(./solution_cpp < tests/test.cpp)
          echo "$OUTPUT"
          echo "$OUTPUT" | tee results.log

      - name: Run Python Program
        if: steps.filter.outputs.python == 'true'
        run: |
          OUTPUT=$(python3 solutions/main.py < tests/test.py)
          echo "$OUTPUT"
          echo "$OUTPUT" | tee results.log

      - name: Compile and Run Java Program
        if: steps.filter.outputs.java == 'true'
        run: |
          javac solutions/Main.java
          OUTPUT=$(java -cp solutions Main < tests/MainTest.java)
          echo "$OUTPUT"
          echo "$OUTPUT" | tee results.log

      - name: Count Passed Test Cases
        run: |
          if [ ! -s results.log ]; then
            echo "No output found. Exiting..."
            exit 1
          fi
          
          TOTAL_TESTS=$(wc -l < results.log)
          PASSED_TESTS=$(grep -c "PASSED" results.log || true)
          FAILED_TESTS=$((TOTAL_TESTS - PASSED_TESTS))
          
          echo "### Test Summary Report ###"
          echo "Total: $TOTAL_TESTS"
          echo "✅ Passed: $PASSED_TESTS"
          echo "❌ Failed: $FAILED_TESTS"
          
          echo "TOTAL_TESTS=$TOTAL_TESTS" >> $GITHUB_ENV
          echo "PASSED_TESTS=$PASSED_TESTS" >> $GITHUB_ENV
          echo "FAILED_TESTS=$FAILED_TESTS" >> $GITHUB_ENV
